### ISSUE TITLE
对于Linux的教程不理解

### ISSUE THREAD

**Issue by LookStars** [KuriYama-mirai524/bike_search#1]
参考的教程相对比较完整，但是在最后一个额外内容那一块就开始不完整了，反而这个插件和额外内容的描述出现的报错一模一样（总之我的一模一样）
（额外内容）运行chromedriver，需要自行添加代码 但是作者也没有说往哪里加 我也不知道往哪里加 一头雾水 希望大佬能帮忙解答一下
这里附上报错日志
[root@GreenCloud Search]# python3 main.py
当前引擎: 萌娘百科
简略模式: 否
获取会话...
{'code': 0, 'msg': 'success'}
bot连接成功!
启用该功能的群: [965270152]
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    web = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

[root@GreenCloud Search]#

**Comment by LookStars** [comment]
![image](https://user-images.githubusercontent.com/79433682/183098443-1266f2bf-c421-47ef-9e71-22e5dc57d716.png)
他说 这里需要为driver进行设置,那么要在哪里设置呢 我不知道 然后我就尝试着直接在main.py里加 事实上不行 会报错...

**Comment by KuriYama-mirai524** [comment]
> 

不用自行设置chromedriver，那些已经包含在main.py里了，不需要跟着教程自己写一个test.py，只需要保证下载的chromedriver和chrome的版本一致即可

**Comment by KuriYama-mirai524** [comment]
> ![image](https://user-images.githubusercontent.com/79433682/183098443-1266f2bf-c421-47ef-9e71-22e5dc57d716.png) 他说 这里需要为driver进行设置,那么要在哪里设置呢 我不知道 然后我就尝试着直接在main.py里加 事实上不行 会报错...

今天我也遇到了这个问题，解决方法是在main.py里找到这一行，添加一个设置就可以了，或者可以重新下载我的源码，已经改过了
![image](https://user-images.githubusercontent.com/93362741/183331961-40e281c2-877d-48cf-a441-5da1f8268496.png)

**Comment by LookStars** [comment]
> > ![图片](https://user-images.githubusercontent.com/79433682/183098443-1266f2bf-c421-47ef-9e71-22e5dc57d716.png)他说我这里需要在哪里设置呢，然后我试了一下在main.py里就可以为知道如何设置驱动程序直接进行会报错...
> 
> 我今天也遇到了这个问题，解决方法是在main.py里找到这一行，添加一个设置就可以了，或者可以重新下载我的源码，已经改了 ![图片](https://user-images.githubusercontent.com/93362741/183331961-40e281c2-877d-48cf-a441-5da1f8268496.png)

谢谢 已经好了 麻烦大佬了，CSDN教程说为driver加入这段设置的时候我是真的没看懂 可能是因为我笨吧..
