### ISSUE TITLE
关于截图会乱码的问题

### ISSUE THREAD

**Issue by LookStars** [KuriYama-mirai524/bike_search#2]
![VSL3`HBG FCQC{GXNA0Q~1D](https://user-images.githubusercontent.com/79433682/183337984-05f9b92f-aeed-4ad7-a8fd-3ab4ba28e271.png)
![P`@$I5)LF3D%G7RJA1RUJO3](https://user-images.githubusercontent.com/79433682/183338004-12bd8a87-20fc-45db-83b1-3d553597ef4d.png)

**Comment by KuriYama-mirai524** [comment]
尝试安装中文字体解决，[参考](https://blog.csdn.net/Happy_Sunshine_Boy/article/details/123204457?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165993233616780357250721%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165993233616780357250721&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-123204457-null-null.142^v39^pc_rank_34_ecpm25,185^v2^control&utm_term=selenium%E6%88%AA%E5%9B%BE%E4%B9%B1%E7%A0%81&spm=1018.2226.3001.4187)
